name: pkgportal
services:
  pkgportal-db:
    image: ghcr.io/eps-dockermanager/pkgportal-db:${ENV_IMAGE_VER}
    container_name: pkgportal-db
    volumes:
      - ./data/pkgportal-db_data:/var/lib/postgresql/data
      # - ./data/logs/postgres:/var/log/postgresql
    environment:
      POSTGRES_DB: pkgportal
      POSTGRES_USER: pkgportaluser
      POSTGRES_PASSWORD: pkgportalpwd
      KEYCLOAK_DB: keycloak
      KEYCLOAK_DB_USERNAME: keycloakuser
      KEYCLOAK_DB_PASSWORD: keycloakpwd
    ports:
      - '5434:5432'
    networks:
      - pkgportal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1024MB'
  keycloak:
    image: ghcr.io/eps-dockermanager/pkgportal-im:${ENV_IMAGE_VER}
    container_name: keycloak-im
    hostname: keycloak-im
    depends_on:
      pkgportal-db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pkgportal-db:5432/keycloak
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpwd
      KEYCLOAK_ADMIN: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KEYCLOAK_ACCESS_TOKEN_LIFESPAN: 1h
      KEYCLOAK_LOGLEVEL: ALL
      KC_HOSTNAME_STRICT: false
      KC_EDGE: proxy
      KC_METRICS_PROMETHEUS: true
      KC_HTTP_MANAGEMENT_PORT: 9000
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_PORT: 8084
      KC_HTTPS_PORT: 443
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME: http://keycloak-im:8084
    ports:
      - '8084:8084'
    networks:
      - pkgportal-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8084/health/ready"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1024M'
  pkgportal-api:
    image: ghcr.io/eps-dockermanager/pkgportal-api:${ENV_IMAGE_VER}
    container_name: pkgportal-api
    depends_on:
      redis:
        condition: service_healthy
      pkgportal-databridge:
        condition: service_started
      pkgportal-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5020/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      HTTP_PORTS: 5020
    volumes:
      - ./data/reports:/App/reports
      - ./data/pkgportal-api_data:/App/data
      - ./data/logs:/App/Logs
    networks:
      - pkgportal-network
  pkgportal-databridge:
    image: ghcr.io/eps-dockermanager/pkgportal-databridge:${ENV_IMAGE_VER}
    container_name: pkgportal-databridge
    depends_on:
      redis:
        condition: service_healthy
      liquibase-update:
        condition: service_completed_successfully
      pkgportal-db:
        condition: service_healthy
    volumes:
      - ./data/logs:/App/Logs
    environment:
      HTTP_PORTS: 5021
    networks:
      - pkgportal-network
  pkgportal-dataexporter:
    image: ghcr.io/eps-dockermanager/pkgportal-dataexporter:${ENV_IMAGE_VER}
    container_name: pkgportal-dataexporter
    depends_on:
      redis:
        condition: service_healthy
      liquibase-update:
        condition: service_completed_successfully
      pkgportal-db:
        condition: service_healthy
    environment:
      HTTP_PORTS: 5022
    volumes:
      - ./data/reports:/App/reports
      - ./data/pkgportal-api_data:/App/data
      - ./data/logs:/App/Logs
    networks:
      - pkgportal-network
  notification:
    image: ghcr.io/eps-dockermanager/pkgportal-notification:${ENV_IMAGE_VER}
    container_name: notification
    depends_on:
      redis:
        condition: service_healthy
      liquibase-update:
        condition: service_completed_successfully
      pkgportal-db:
        condition: service_healthy
    environment:
      HTTP_PORTS: 5028
    volumes:
      - ./data/pkgportal-api_data:/App/data
      - ./data/logs:/App/Logs
    networks:
      - pkgportal-network
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pkgportal-network
  nginx-web:
    image: ghcr.io/eps-dockermanager/pkgportal-web:${ENV_IMAGE_VER}
    container_name: weblb
    ports:
      - 8083:83
      - 8443:443
    networks:
      - pkgportal-network
    volumes:
      - ./data/nginx/cert:/cert
  liquibase-update:
    image: ghcr.io/eps-dockermanager/pkgportal-dbmanager:${ENV_IMAGE_VER}
    container_name: liquibase-update
    depends_on:
      pkgportal-db:
        condition: service_healthy
    environment:
    - LIQUIBASE_COMMAND_URL=jdbc:postgresql://pkgportal-db:5432/pkgportal
    - LIQUIBASE_COMMAND_CHANGELOG_FILE=/changelog.xml
    - LIQUIBASE_COMMAND_USERNAME=pkgportaluser
    - LIQUIBASE_COMMAND_PASSWORD=pkgportalpwd
    command: liquibase update
    networks:
      - pkgportal-network
  prometheus:
    image: ghcr.io/eps-dockermanager/custom-prometheus:${ENV_IMAGE_VER}
    container_name: prometheus
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./data/prometheus_data:/prometheus
    networks:
      - pkgportal-network
  grafana:
    image: ghcr.io/eps-dockermanager/custom-grafana:${ENV_IMAGE_VER}
    container_name: grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
     - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana_data:/var/lib/grafana
    networks:
      - pkgportal-network
  postgres-exporter:
    image: ghcr.io/eps-dockermanager/custom-postgres-exporter:${ENV_IMAGE_VER}
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: "pkgportal-db:5432/pkgportal?sslmode=disable"
      DATA_SOURCE_USER: pkgportaluser
      DATA_SOURCE_PASS: pkgportalpwd
      EXTENSION: "pg_stat_statements"
    command:
      - "--extend.query-path=/etc/custom-queries.yaml"
    depends_on:
      pkgportal-db:
        condition: service_healthy
    networks:
      - pkgportal-network
  pg-vector:
    image: ghcr.io/eps-dockermanager/pgvector:v12.1.23
    container_name: pg-vector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipwd
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiuser -d ai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pkgportal-network
  ai-agent:
    image: ghcr.io/eps-dockermanager/ai-agent:v12.1.23
    container_name: ai-agent
    environment:
      POSTGRES_PORT: 5432
      CSR_BASE_URL: http://pkgportal-api:5020
    ports:
      - "5023:5023"
    depends_on:
      pg-vector:
        condition: service_healthy
    networks:
      - pkgportal-network
networks:
  pkgportal-network: {}