name: pkgportal
services:  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pkgportal-network
networks:
  pkgportal-network: {}
volumes:
  shared-data:
    driver: local
