version: "3.8"
name: eflow
services:
  eflow:
    image: custom-eflow:${TAG_NAME}
    container_name: eflow
    build:
      context: .
      args:
        EFLOW_VERSION: ${EFLOW_VERSION}
        STATE: ${EFLOW_STATE}
        CENTRAL_EFLOW: ${EFLOW_CENTRAL_EFLOW}
        EMAIL: ${EFLOW_EMAIL}
        COMPANY: ${EFLOW_COMPANY}
        MACHINENAME: ${EFLOW_MACHINENAME}
    ports:
      - "8081:8081"
      - "6543:6543"
      - "6161:6161"
      - "9200:9200"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: '6144MB'
    networks:
      - eflow-network
    volumes:
      - eflow-instance:/eflow/instance:rw
      - eflow-logs:/eflow/logs:rw
      - eflow-es-data:/var/lib/elasticsearch:rw
      - eflow-es-logs:/var/log/elasticsearch:rw
      - eflow-dbbackup:/eflow/dbbackup:rw
      - eflow-db:/var/lib/postgresql/17/main/:rw
networks:
  eflow-network:
    driver: bridge
volumes:
  eflow-instance: {}
  eflow-logs: {}
  eflow-es-data: {}
  eflow-es-logs: {}
  eflow-dbbackup: {}
  eflow-db: {}